### ISSUE TITLE
Add top level README.md that indicates main URL

### ISSUE THREAD

**Issue by dsolovay** [Velir/Jabberwocky-docs#3]

**Comment by smithc** [comment]
Nice Dan, thanks.  Can you actually change the URL to point to: jabberwocky.rtfd.org?

We've made the documentation public, so they're now hosted at readthedocs.

**Comment by dsolovay** [comment]
Currently it is http://jabberwocky.readthedocs.org. Do you prefer the shortened rtfd.org?

**Comment by smithc** [comment]
Either works, although I do like the (not so subtle) RTFD acronym.

**Comment by dsolovay** [comment]
Done!
